### ISSUE TITLE
Question about benchmark_with_tensors

### ISSUE THREAD

**Issue by prnake** [facebookincubator/AITemplate#96]
Thanks for your awsome work. When I'm trying to evaluate the running time, I find that `module.benchmark_with_tensors` is pretty much faster than using `module.run_with_tensor` with iters, so I wonder where the difference in time costs come from.

```python
count = 1000
ait_t, _, _ = module.benchmark_with_tensors(
    inputs, outputs, graph_mode=True, count=count
)
print(f"AITemplate time: {ait_t} ms/iter")

import time
t0 = time.time()
for _ in range(count):
  y = module.run_with_tensors(inputs, outputs, graph_mode=True)
print(f"AITemplate time: {(time.time()-t0)/count*1000} ms/iter")

pt_t = benchmark_torch_function(count, pt_model.forward, x)
print(f"PyTorch eager time: {pt_t} ms/iter")
```

And the results are:

```
AITemplate time: 0.06172141060233116 ms/iter
AITemplate time: 0.11695981025695801 ms/iter
PyTorch eager time: 0.11286835479736328 ms/ite
```

**Comment by mikeiovine** [comment]
There's some optional synchronization in `run_with_tensors`:

* When you do `run_with_tensors`, it synchronizes with the stream you run on by default. So in your example, you're doing a full stream sync every iteration.
* On the other hand, in the benchmarking function, we invoke `Run` `count` times and then synchronize it all at the end.

You can try setting `sync=False` in `run_with_tensors` to get more comparable performance. You can also use `torch.cuda.Event`s instead of `time` for more accurate results. Remember to synchronize the stream at the end of the `for` loop before measuring the time!

**Comment by prnake** [comment]
Thanks for the explanation
